apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nakarth-com-tls
spec:
  secretName: nakarth-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nakarth.com
  dnsNames:
    - nakarth.com
    - www.nakarth.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - nakarth.com
      - www.nakarth.com
